/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package unipar.br.oficina;

/**
 *
 * @author jjoao
 */


import javax.swing.*;
import java.awt.*;
import unipar.br.oficina.Cliente;
import unipar.br.oficina.OrdemServico;
import unipar.br.oficina.Veiculo;

public class ClienteVeiculoPanel extends JPanel {
    private OrdemServico os;
    private JTextField tfNomeCliente, tfContato, tfEndereco;
    private JTextField tfMarca, tfModelo, tfAno, tfPlaca;

    public ClienteVeiculoPanel(OrdemServico os) {
        this.os = os;
        setLayout(new GridLayout(0, 2, 5, 5));

        add(new JLabel("Nome do Cliente:"));
        tfNomeCliente = new JTextField();
        add(tfNomeCliente);

        add(new JLabel("Contato:"));
        tfContato = new JTextField();
        add(tfContato);

        add(new JLabel("Endereço:"));
        tfEndereco = new JTextField();
        add(tfEndereco);

        add(new JLabel("Marca:"));
        tfMarca = new JTextField();
        add(tfMarca);

        add(new JLabel("Modelo:"));
        tfModelo = new JTextField();
        add(tfModelo);

        add(new JLabel("Ano:"));
        tfAno = new JTextField();
        add(tfAno);

        add(new JLabel("Placa:"));
        tfPlaca = new JTextField();
        add(tfPlaca);

        JButton btnSalvar = new JButton("Salvar");
        btnSalvar.addActionListener(e -> salvarDados());
        add(btnSalvar);
    }

    private void salvarDados() {
        if (tfNomeCliente.getText().isEmpty() || tfPlaca.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Preencha todos os campos obrigatórios!");
            return;
        }

        Cliente cliente = new Cliente();
        cliente.setNome(tfNomeCliente.getText());
        cliente.setContato(tfContato.getText());
        cliente.setEndereco(tfEndereco.getText());

        Veiculo veiculo = new Veiculo();
        veiculo.setMarca(tfMarca.getText());
        veiculo.setModelo(tfModelo.getText());
        veiculo.setAno(Integer.parseInt(tfAno.getText()));
        veiculo.setPlaca(tfPlaca.getText());

        os.setCliente(cliente);
        os.setVeiculo(veiculo);

        JOptionPane.showMessageDialog(this, "Dados salvos com sucesso!");
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
