/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package unipar.br.oficina;

/**
 *
 * @author jjoao
 */


import javax.swing.*;
import java.awt.event.ActionEvent;
import java.util.ArrayList;
import java.util.List;
import unipar.br.oficina.Usuario;

public class LoginFrame extends JFrame {
    private JTextField tfNome;
    private JPasswordField tfSenha;
    private List<Usuario> usuarios = new ArrayList<>();

    public LoginFrame() {
        setTitle("Login - Oficina Mecânica");
        setSize(300, 200);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        // Usuário padrão
        usuarios.add(new Usuario("admin", "12345678900"));

        JPanel panel = new JPanel();
        panel.setLayout(new BoxLayout(panel, BoxLayout.Y_AXIS));

        JLabel lblNome = new JLabel("Nome:");
        tfNome = new JTextField(15);

        JLabel lblSenha = new JLabel("CPF (Senha):");
        tfSenha = new JPasswordField(15);

        JButton btnLogin = new JButton("Login");
        JButton btnCadastrar = new JButton("Cadastrar Novo Usuário");

        btnLogin.addActionListener(this::validarLogin);
        btnCadastrar.addActionListener(this::cadastrarUsuario);

        panel.add(lblNome);
        panel.add(tfNome);
        panel.add(lblSenha);
        panel.add(tfSenha);
        panel.add(btnLogin);
        panel.add(btnCadastrar);

        add(panel);
    }

    private void validarLogin(ActionEvent e) {
        String nome = tfNome.getText().trim();
        String cpf = new String(tfSenha.getPassword()).replaceAll("[^0-9]", "");

        if (nome.isEmpty() || cpf.length() != 11) {
            JOptionPane.showMessageDialog(this, "Nome ou CPF inválido!");
            return;
        }

        for (Usuario usuario : usuarios) {
            if (usuario.getNome().equals(nome) && usuario.getCpf().equals(cpf)) {
                JOptionPane.showMessageDialog(this, "Login realizado com sucesso!");
                new MainFrame().setVisible(true);
                this.dispose();
                return;
            }
        }

        JOptionPane.showMessageDialog(this, "Usuário ou senha incorretos!");
    }

    private void cadastrarUsuario(ActionEvent e) {
        String nome = JOptionPane.showInputDialog(this, "Digite o nome do novo usuário:");
        String cpf = JOptionPane.showInputDialog(this, "Digite o CPF (senha):");

        if (nome != null && cpf != null && cpf.matches("\\d{11}")) {
            usuarios.add(new Usuario(nome, cpf));
            JOptionPane.showMessageDialog(this, "Usuário cadastrado com sucesso!");
        } else {
            JOptionPane.showMessageDialog(this, "CPF inválido (deve ter 11 dígitos)!");
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

