/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package unipar.br.oficina;

/**
 *
 * @author jjoao
 */


import javax.swing.*;
import java.awt.*;
import unipar.br.oficina.OrdemServico;
import unipar.br.oficina.Peca;
import unipar.br.oficina.Servico;

public class OSPanel extends JPanel {
    private OrdemServico os;
    private JTextArea taOS;

    public OSPanel(OrdemServico os) {
        this.os = os;
        setLayout(new BorderLayout());

        taOS = new JTextArea();
        taOS.setEditable(false);
        JScrollPane scrollPane = new JScrollPane(taOS);
        add(scrollPane, BorderLayout.CENTER);

        JButton btnGerarOS = new JButton("Gerar Ordem de Serviço");
        btnGerarOS.addActionListener(e -> gerarOS());
        add(btnGerarOS, BorderLayout.SOUTH);
    }

    private void gerarOS() {
        if (os.getCliente() == null || os.getVeiculo() == null) {
            JOptionPane.showMessageDialog(this, "Preencha os dados do cliente e veículo primeiro!");
            return;
        }

        StringBuilder sb = new StringBuilder();
        sb.append("=== ORDEM DE SERVIÇO ===\n\n");
        sb.append("Cliente: ").append(os.getCliente().getNome()).append("\n");
        sb.append("Contato: ").append(os.getCliente().getContato()).append("\n");
        sb.append("Endereço: ").append(os.getCliente().getEndereco()).append("\n\n");
        sb.append("Veículo: ").append(os.getVeiculo().getMarca()).append(" ").append(os.getVeiculo().getModelo()).append("\n");
        sb.append("Ano: ").append(os.getVeiculo().getAno()).append("\n");
        sb.append("Placa: ").append(os.getVeiculo().getPlaca()).append("\n\n");
        sb.append("=== SERVIÇOS ===\n");

        double totalServicos = 0;
        for (Servico servico : os.getServicos()) {
            sb.append("- ").append(servico.getDescricao()).append(": R$ ").append(servico.getCusto()).append("\n");
            totalServicos += servico.getCusto();
        }

        sb.append("\n=== PEÇAS ===\n");
        double totalPecas = 0;
        for (Peca peca : os.getPecas()) {
            sb.append("- ").append(peca.getNome()).append(" (x").append(peca.getQuantidade()).append("): R$ ").append(peca.getPrecoUnitario()).append("\n");
            totalPecas += (peca.getQuantidade() * peca.getPrecoUnitario());
        }

        sb.append("\n=== TOTAL ===\n");
        sb.append("Serviços: R$ ").append(totalServicos).append("\n");
        sb.append("Peças: R$ ").append(totalPecas).append("\n");
        sb.append("TOTAL GERAL: R$ ").append(totalServicos + totalPecas);

        taOS.setText(sb.toString());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

