package unipar.br.oficina;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */


/**
 *
 * @author jjoao
 */


import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import unipar.br.oficina.OrdemServico;

public class PecasPanel extends JPanel {
    private OrdemServico os;
    private DefaultTableModel modeloPecas;
    private JTable tabelaPecas;

    public PecasPanel(OrdemServico os) {
        this.os = os;
        setLayout(new BorderLayout());

        modeloPecas = new DefaultTableModel();
        modeloPecas.addColumn("Peça");
        modeloPecas.addColumn("Quantidade");
        modeloPecas.addColumn("Preço Unitário");

        tabelaPecas = new JTable(modeloPecas);
        JScrollPane scrollPane = new JScrollPane(tabelaPecas);
        add(scrollPane, BorderLayout.CENTER);

        JButton btnAdicionar = new JButton("Adicionar Peça");
        btnAdicionar.addActionListener(e -> adicionarPeca());
        add(btnAdicionar, BorderLayout.SOUTH);
    }

    private void adicionarPeca() {
        String nome = JOptionPane.showInputDialog(this, "Nome da peça:");
        String qtdStr = JOptionPane.showInputDialog(this, "Quantidade:");
        String precoStr = JOptionPane.showInputDialog(this, "Preço unitário (R$):");

        if (nome != null && !nome.isEmpty() && qtdStr != null && precoStr != null) {
            try {
                int quantidade = Integer.parseInt(qtdStr);
                double preco = Double.parseDouble(precoStr);
                Peca peca = new Peca(nome, quantidade, preco);
                os.getPecas().add(peca);
                modeloPecas.addRow(new Object[]{nome, quantidade, preco});
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor inválido!");
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
