/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package unipar.br.oficina;

/**
 *
 * @author jjoao
 */

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import unipar.br.oficina.OrdemServico;
import unipar.br.oficina.Servico;

public class ServicosPanel extends JPanel {
    private OrdemServico os;
    private DefaultTableModel modeloServicos;
    private JTable tabelaServicos;

    public ServicosPanel(OrdemServico os) {
        this.os = os;
        setLayout(new BorderLayout());

        modeloServicos = new DefaultTableModel();
        modeloServicos.addColumn("Descrição");
        modeloServicos.addColumn("Custo (R$)");

        tabelaServicos = new JTable(modeloServicos);
        JScrollPane scrollPane = new JScrollPane(tabelaServicos);
        add(scrollPane, BorderLayout.CENTER);

        JButton btnAdicionar = new JButton("Adicionar Serviço");
        btnAdicionar.addActionListener(e -> adicionarServico());
        add(btnAdicionar, BorderLayout.SOUTH);
    }

    private void adicionarServico() {
        String descricao = JOptionPane.showInputDialog(this, "Descrição do serviço:");
        String custoStr = JOptionPane.showInputDialog(this, "Custo (R$):");

        if (descricao != null && !descricao.isEmpty() && custoStr != null) {
            try {
                double custo = Double.parseDouble(custoStr);
                Servico servico = new Servico(descricao, custo);
                os.getServicos().add(servico);
                modeloServicos.addRow(new Object[]{descricao, custo});
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Valor inválido!");
            }
        }
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

